package com.xinto.opencord.ui.theme

import androidx.compose.ui.graphics.Color

//main
val ColorLightPrimary = Color(0xFF3F4CDA)
val ColorLightOnPrimary = Color(0xFFFFFFFF)
val ColorLightPrimaryContainer = Color(0xFFE0E0FF)
val ColorLightOnPrimaryContainer = Color(0xFF000569)
val ColorLightSecondary = Color(0xFF5C5D72)
val ColorLightOnSecondary = Color(0xFFFFFFFF)
val ColorLightSecondaryContainer = Color(0xFFE1E0F9)
val ColorLightOnSecondaryContainer = Color(0xFF191A2C)
val ColorLightTertiary = Color(0xFF78536B)
val ColorLightOnTertiary = Color(0xFFFFFFFF)
val ColorLightTertiaryContainer = Color(0xFFFFD7EE)
val ColorLightOnTertiaryContainer = Color(0xFF2E1126)
val ColorLightError = Color(0xFFBA1A1A)
val ColorLightErrorContainer = Color(0xFFFFDAD6)
val ColorLightOnError = Color(0xFFFFFFFF)
val ColorLightOnErrorContainer = Color(0xFF410002)
val ColorLightBackground = Color(0xFFFFFBFF)
val ColorLightOnBackground = Color(0xFF1B1B1F)
val ColorLightSurface = Color(0xFFFFFBFF)
val ColorLightOnSurface = Color(0xFF1B1B1F)
val ColorLightSurfaceVariant = Color(0xFFE3E1EC)
val ColorLightOnSurfaceVariant = Color(0xFF46464F)
val ColorLightOutline = Color(0xFF777680)
val ColorLightInverseOnSurface = Color(0xFFF3F0F4)
val ColorLightInverseSurface = Color(0xFF303034)
val ColorLightInversePrimary = Color(0xFFBEC2FF)
val ColorLightSurfaceTint = Color(0xFF3F4CDA)
val ColorLightOutlineVariant = Color(0xFFC7C5D0)
val ColorLightScrim = Color(0xFF000000)

val ColorDarkPrimary = Color(0xFFBEC2FF)
val ColorDarkOnPrimary = Color(0xFF000DA4)
val ColorDarkPrimaryContainer = Color(0xFF222FC2)
val ColorDarkOnPrimaryContainer = Color(0xFFE0E0FF)
val ColorDarkSecondary = Color(0xFFC5C4DD)
val ColorDarkOnSecondary = Color(0xFF2E2F42)
val ColorDarkSecondaryContainer = Color(0xFF444559)
val ColorDarkOnSecondaryContainer = Color(0xFFE1E0F9)
val ColorDarkTertiary = Color(0xFFE7B9D5)
val ColorDarkOnTertiary = Color(0xFF45263C)
val ColorDarkTertiaryContainer = Color(0xFF5E3C53)
val ColorDarkOnTertiaryContainer = Color(0xFFFFD7EE)
val ColorDarkError = Color(0xFFFFB4AB)
val ColorDarkErrorContainer = Color(0xFF93000A)
val ColorDarkOnError = Color(0xFF690005)
val ColorDarkOnErrorContainer = Color(0xFFFFDAD6)
val ColorDarkBackground = Color(0xFF1B1B1F)
val ColorDarkOnBackground = Color(0xFFE4E1E6)
val ColorDarkSurface = Color(0xFF1B1B1F)
val ColorDarkOnSurface = Color(0xFFE4E1E6)
val ColorDarkSurfaceVariant = Color(0xFF46464F)
val ColorDarkOnSurfaceVariant = Color(0xFFC7C5D0)
val ColorDarkOutline = Color(0xFF91909A)
val ColorDarkInverseOnSurface = Color(0xFF1B1B1F)
val ColorDarkInverseSurface = Color(0xFFE4E1E6)
val ColorDarkInversePrimary = Color(0xFF3F4CDA)
val ColorDarkSurfaceTint = Color(0xFFBEC2FF)
val ColorDarkOutlineVariant = Color(0xFF46464F)
val ColorDarkScrim = Color(0xFF000000)

//extended
val ColorExtendedLightSuccess = Color(0xFF006D31)
val ColorExtendedLightOnSuccess = Color(0xFFFFFFFF)
val ColorExtendedLightSuccessContainer = Color(0xFF65FF90)
val ColorExtendedLightOnSuccessContainer = Color(0xFF00210A)
val ColorExtendedLightWarning = Color(0xFF6B5F00)
val ColorExtendedLightOnWarning = Color(0xFFFFFFFF)
val ColorExtendedLightWarningContainer = Color(0xFFFAE359)
val ColorExtendedLightOnWarningContainer = Color(0xFF201C00)
val ColorExtendedLightInfo = Color(0xFFB40D73)
val ColorExtendedLightOnInfo = Color(0xFFFFFFFF)
val ColorExtendedLightInfoContainer = Color(0xFFFFD8E6)
val ColorExtendedLightOnInfoContainer = Color(0xFF3D0024)
val ColorExtendedDarkSuccess = Color(0xFF43E277)
val ColorExtendedDarkOnSuccess = Color(0xFF003916)
val ColorExtendedDarkSuccessContainer = Color(0xFF005323)
val ColorExtendedDarkOnSuccessContainer = Color(0xFF65FF90)
val ColorExtendedDarkWarning = Color(0xFFDDC73F)
val ColorExtendedDarkOnWarning = Color(0xFF383000)
val ColorExtendedDarkWarningContainer = Color(0xFF514700)
val ColorExtendedDarkOnWarningContainer = Color(0xFFFAE359)
val ColorExtendedDarkInfo = Color(0xFFFFB0D0)
val ColorExtendedDarkOnInfo = Color(0xFF63003D)
val ColorExtendedDarkInfoContainer = Color(0xFF8C0057)
val ColorExtendedDarkOnInfoContainer = Color(0xFFFFD8E6)

//seed
val Blurple = Color(0xFF5865F2)
val Green = Color(0xFF57F285)
val Yellow = Color(0xFFFEE75C)
val Fuchsia = Color(0xFFEB459E)
