package com.xinto.opencord.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF3f4cda)
val LightOnPrimary = Color(0xFFffffff)
val LightPrimaryContainer = Color(0xFFdfe0ff)
val LightOnPrimaryContainer = Color(0xFF00006f)
val LightSecondary = Color(0xFF5c5d71)
val LightOnSecondary = Color(0xFFffffff)
val LightSecondaryContainer = Color(0xFFe1e0f9)
val LightOnSecondaryContainer = Color(0xFF181a2c)
val LightTertiary = Color(0xFF78536b)
val LightOnTertiary = Color(0xFFffffff)
val LightTertiaryContainer = Color(0xFFffd7f0)
val LightOnTertiaryContainer = Color(0xFF2e1126)
val LightError = Color(0xFFba1b1b)
val LightErrorContainer = Color(0xFFffdad4)
val LightOnError = Color(0xFFffffff)
val LightOnErrorContainer = Color(0xFF410001)
val LightBackground = Color(0xFFfffbff)
val LightOnBackground = Color(0xFF1b1b1f)
val LightSurface = Color(0xFFfffbff)
val LightOnSurface = Color(0xFF1b1b1f)
val LightSurfaceVariant = Color(0xFFe3e1ec)
val LightOnSurfaceVariant = Color(0xFF46464f)
val LightOutline = Color(0xFF77767f)
val LightInverseOnSurface = Color(0xFFf3f0f5)
val LightInverseSurface = Color(0xFF303034)
val LightInversePrimary = Color(0xFFbcc2ff)

val DarkPrimary = Color(0xFFbcc2ff)
val DarkOnPrimary = Color(0xFF0002ac)
val DarkPrimaryContainer = Color(0xFF222fc2)
val DarkOnPrimaryContainer = Color(0xFFdfe0ff)
val DarkSecondary = Color(0xFFc4c4dc)
val DarkOnSecondary = Color(0xFF2e2f42)
val DarkSecondaryContainer = Color(0xFF444559)
val DarkOnSecondaryContainer = Color(0xFFe1e0f9)
val DarkTertiary = Color(0xFFe7b9d5)
val DarkOnTertiary = Color(0xFF46263c)
val DarkTertiaryContainer = Color(0xFF5e3c53)
val DarkOnTertiaryContainer = Color(0xFFffd7f0)
val DarkError = Color(0xFFffb4a9)
val DarkErrorContainer = Color(0xFF930006)
val DarkOnError = Color(0xFF680003)
val DarkOnErrorContainer = Color(0xFFffdad4)
val DarkBackground = Color(0xFF1b1b1f)
val DarkOnBackground = Color(0xFFe4e1e6)
val DarkSurface = Color(0xFF1b1b1f)
val DarkOnSurface = Color(0xFFe4e1e6)
val DarkSurfaceVariant = Color(0xFF46464f)
val DarkOnSurfaceVariant = Color(0xFFc7c5cf)
val DarkOutline = Color(0xFF91909a)
val DarkInverseOnSurface = Color(0xFF1b1b1f)
val DarkInverseSurface = Color(0xFFe4e1e6)
val DarkInversePrimary = Color(0xFF3f4cda)

val DiscordBlurple = Color(0xFF5865f2)
val DiscordGreen = Color(0xFF57f285)
val DiscordYellow = Color(0xFFfee75c)
val DiscordFuchsia = Color(0xFFeb459e)
val DiscordRed = Color(0xFFed4245)